working_dir: "."
data_dir: "./data"
config_dir: "./config"
pid_dir: "./"
log_dir: "./logs"
log_mode: "stdout"
log_level: info
profiling: false
sqlite_path: "./test.db"
apimode: false
plugin:
  backend: "./config/plugins/backend"
